-- AlterTable
ALTER TABLE "Account" ALTER COLUMN "role" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Session" ALTER COLUMN "role" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "role" DROP DEFAULT;
